# Generated by Django 3.1.1 on 2020-10-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uwapp', '0002_auto_20200928_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttraining',
            old_name='data_opublikowania',
            new_name='published_date',
        ),
    ]
